/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-05-13 10:18:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/footerbar.jsp", Long.valueOf(1620901111576L));
    _jspx_dependants.put("/views/common/mainPage.jsp", Long.valueOf(1620900915455L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1620900899661L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t* 회원서비스\t\t| C (Insert) | R (Select) | U (Update) | D (Delete)\r\n");
      out.write("\t\t==============================================================================\r\n");
      out.write("\t\t\t로그인\t\t|\t\t\t |\t\tO\t  |\t\t\t   |\r\n");
      out.write("\t\t   \t회원가입\t\t|\t  O\t\t |\t\t\t  |\t\t\t   |\r\n");
      out.write("\t\t [아이디중복확인]\t|\t\t\t |\t\tO\t  | \t\t   |\r\n");
      out.write("\t\t   \t마이페이지\t\t|\t\t\t |\t\tO\t  |\t\t\t   | \r\n");
      out.write("\t\t   \t정보변경\t\t|\t\t\t |\t\t\t  |\t\tO\t   |\r\n");
      out.write("\t\t\t회원탈퇴\t\t|\t\t\t |\t\t\t  |\t\tO\t   |\t O\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t* 공지사항서비스 - 공지사항리스트조회(R)/공지사항상세조회(R)/공지사항작성(C)/공지사항수정(U)/공지사항삭제(U|D)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t* 일반게시판서비스 - 게시판리스트조회(R)-페이징처리/게시판상세조회(R)/게시판작성(C)-첨부파일1개업로드/\r\n");
      out.write("\t\t\t\t\t\t 게시판수정(U)/게시판삭제(U|D)/[댓글리스트조회(R)/댓글작성(C)]\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t* 사진게시판서비스 - 게시판리스트조회(R)-썸네일/게시판상세조회(R)/게시판작성(C)-다중첨부파일업로드\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("      \r\n");
      out.write("    .body{\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        height: 1240px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write("    .img1{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("     .careing{\r\n");
      out.write("        height: 20%;\r\n");
      out.write("        \r\n");
      out.write("     }\r\n");
      out.write("     .adoption{\r\n");
      out.write("        height: 20%;\r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("    .extitle{\r\n");
      out.write("        height: 15%;\r\n");
      out.write("        color: rgb(94, 94, 94);\r\n");
      out.write("        font-family: HanSans; \r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-align: left; \r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .careingimg{\r\n");
      out.write("         height: 65%;\r\n");
      out.write("         width: 100%;       \r\n");
      out.write("         \r\n");
      out.write("    }\r\n");
      out.write("    .more{\r\n");
      out.write("        height: 15%;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    .animalimg{\r\n");
      out.write("        width: 23%;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin: 10px;        \r\n");
      out.write("    }\r\n");
      out.write("    .animalimg>img{\r\n");
      out.write("        width:261px;\r\n");
      out.write("        height:188px;\r\n");
      out.write("    }\r\n");
      out.write("        \r\n");
      out.write("    .more>button{\r\n");
      out.write("    font-size: 16px; \r\n");
      out.write("    color: rgb(255, 255, 255); \r\n");
      out.write("    text-align: center; \r\n");
      out.write("    line-height: 2.5em; \r\n");
      out.write("    border-radius: 4px; \r\n");
      out.write("    background-color: rgb(127, 127, 127);\r\n");
      out.write("    border:0px;\r\n");
      out.write("    margin-right: 62px;\r\n");
      out.write("    }\r\n");
      out.write("    .product-title {\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    display:table;\r\n");
      out.write("    border:1px solid #cecece;\r\n");
      out.write("    width:280px;\r\n");
      out.write("    height:250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .on{\r\n");
      out.write("         width: 1200px;\r\n");
      out.write("         height: 180px;         \r\n");
      out.write("         margin: 0 auto;\r\n");
      out.write("         }\r\n");
      out.write("    .mainLogo{\r\n");
      out.write("\r\n");
      out.write("        margin-left: 302px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login {           \r\n");
      out.write("        float:right; \r\n");
      out.write("        margin-top:40px;\r\n");
      out.write("     }\r\n");
      out.write("   #loginform>*{\r\n");
      out.write("    \r\n");
      out.write("    float:left;\r\n");
      out.write("    }\r\n");
      out.write("    .id_pwd{width: 65%; height: 70px; } .loginbtn{width: 35%;}\r\n");
      out.write("\r\n");
      out.write("    .pwd,.id{\r\n");
      out.write("        color: rgb(94, 94, 94);\r\n");
      out.write("        border-style: solid; \r\n");
      out.write("        border-color: rgb(204, 204, 204);\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:50%;\r\n");
      out.write("    }\r\n");
      out.write("    .loginbtn>input{        \r\n");
      out.write("        font-size: 24px; \r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        color: rgb(255, 255, 255); \r\n");
      out.write("        line-height: 3.2em;        \r\n");
      out.write("        background-color: rgb(171, 198, 223); \r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border-radius: 4px;        \r\n");
      out.write("        border:0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .find{\r\n");
      out.write("    text-decoration-line: underline;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 3.2em;      \r\n");
      out.write("    }\r\n");
      out.write("               \r\n");
      out.write("    .navi{\r\n");
      out.write("            width: 1200px; height: 55px;\r\n");
      out.write("            background-color: rgb(187, 208, 227);            \r\n");
      out.write("            margin: 0 auto;         \r\n");
      out.write("     }\r\n");
      out.write("     #navi1{\r\n");
      out.write("            list-style-type:none;\r\n");
      out.write("            margin:0;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        #navi1>li{\r\n");
      out.write("            margin-left: 8px;\r\n");
      out.write("            float:left;\r\n");
      out.write("            width:16%;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("        }\r\n");
      out.write("        #navi1 a{\r\n");
      out.write("            line-height: 2.8em; \r\n");
      out.write("            font-size: 20px; \r\n");
      out.write("            color: rgb(110, 109, 109);\r\n");
      out.write("            font-family: HanSans; \r\n");
      out.write("            width: 16.6%;   \r\n");
      out.write("            font-weight: bold; \r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            display:block;\r\n");
      out.write("            text-decoration:none; \r\n");
      out.write("            z-index: 6;\r\n");
      out.write("        }\r\n");
      out.write("        #navi1 a:hover{color: white;}\r\n");
      out.write("        #navi1>li>ul{\r\n");
      out.write("            list-style-type:none;\r\n");
      out.write("            display:none;           \r\n");
      out.write("            margin-top:0px;\r\n");
      out.write("            padding:10px;\r\n");
      out.write("            background-color: rgb(184, 183, 183); \r\n");
      out.write("            font-family: HanSans;            \r\n");
      out.write("            line-height: 2.8em; \r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 6;\r\n");
      out.write("        }\r\n");
      out.write("        #navi1>li>ul a{font-size:15px;}\r\n");
      out.write("        #navi1>li>a:hover+ul{display:block;}\r\n");
      out.write("        #navi1>li>ul:hover{display:block;}\r\n");
      out.write("     </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"on\">  \r\n");
      out.write("\r\n");
      out.write("                    <image src=\"resources/images/mainLogo.png\" width=\"558px\" height=\"120px\" class=\"mainLogo\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"login\" align=\"center\">\r\n");
      out.write("                   \r\n");
      out.write("                            <form action=\"\" id=\"loginform\">                \r\n");
      out.write("                           \r\n");
      out.write("                                <div class=\"id_pwd\">        \r\n");
      out.write("                                    <input type=\"text\" class=\"id\" value=\"아이디\"><br>\r\n");
      out.write("                                    <input type=\"password\" class=\"pwd\" value=\"비밀번호\" >                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                         \r\n");
      out.write("                                <div class=\"loginbtn\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"login\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>      \r\n");
      out.write("                            <span class=\"find\">ID/PW 찾기 | 회원가입</span>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                       \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navi\">                \r\n");
      out.write("                    <ul id=\"navi1\" >\r\n");
      out.write("                        <li><a href=\"\">코니멀 소개</a></li>\r\n");
      out.write("                        <li><a href=\"\">보호소</a></li>\r\n");
      out.write("                        <li><a href=\"\">입양문의</a>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">보호중인 동물</a></li>\r\n");
      out.write("                                <li><a href=\"\">입양 절차</a></li>\r\n");
      out.write("                                <li><a href=\"\">입양 신청</a></li>\r\n");
      out.write("                                <li><a href=\"\">입양 후기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"\">입소문의</a>                        \r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">입소 절차</a></li>\r\n");
      out.write("                                <li><a href=\"\">입소 신청</a></li>                      \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"\">후원 &amp; 자원봉사</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"\">자원봉사</a></li>\r\n");
      out.write("                            <li><a href=\"\">후원</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                        <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"\">자유 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"\">고객센터</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("            </div>            \r\n");
      out.write("        \r\n");
      out.write("           \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("    \r\n");
      out.write("               \r\n");
      out.write("            <div class=\"body\">\r\n");
      out.write("            <div class=\"imgsilde\">\r\n");
      out.write("                <image src=\"resources/images/slide.png\" class=\"img1\" width= \"1200px\"  height= \"235px\" ></image>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br><br>\r\n");
      out.write("            <div class=\"careing\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"extitle\">\r\n");
      out.write("                    <h3>보호중인 아이들</h3>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"careingimg\">\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\" ></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\" ></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"more\" align=\"right\">\r\n");
      out.write("                    <button>더보기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"adoption\">\r\n");
      out.write("                <div class=\"extitle\">\r\n");
      out.write("                    <h3>입양 후기</h3>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"careingimg\">\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"animalimg\">\r\n");
      out.write("                        <image src=\"resources/images/dog.png\"></image>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"more\" align=\"right\">\r\n");
      out.write("                    <button>더보기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" .footerbar{\r\n");
      out.write("        \r\n");
      out.write("         width: 1200px;\r\n");
      out.write("         height: 180px;\r\n");
      out.write("         margin: 0 auto;\r\n");
      out.write("     }\r\n");
      out.write("     .call{\r\n");
      out.write("         width:30%;\r\n");
      out.write("         height: 100%;\r\n");
      out.write("         float:left;\r\n");
      out.write("         margin-left: 60px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .minLogo{\r\n");
      out.write("                 \r\n");
      out.write("         padding-top: 30px;\r\n");
      out.write("         height: 100%;\r\n");
      out.write("         float:left;  \r\n");
      out.write("     }\r\n");
      out.write("     .ex{\r\n");
      out.write("        width:40%;\r\n");
      out.write("        float:left;        \r\n");
      out.write("        height:100%; \r\n");
      out.write("        padding-top: 25px; \r\n");
      out.write("    }\r\n");
      out.write("     .ect{\r\n");
      out.write("        \r\n");
      out.write("        font-size: 13px; \r\n");
      out.write("        color: rgb(127, 127, 127);\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        width:450px;\r\n");
      out.write("        padding-left: 60px;\r\n");
      out.write("       \r\n");
      out.write("     }\r\n");
      out.write("     .ect2{\r\n");
      out.write("        font-weight: bold; font-size: 24px; text-align: center; color: rgb(94, 94, 94);\r\n");
      out.write("     }\r\n");
      out.write("     .ect3{\r\n");
      out.write("        font-weight: bold; font-size: 33px; text-align: center; color: rgb(94, 94, 94);\r\n");
      out.write("     }\r\n");
      out.write("     #al{                   \r\n");
      out.write("        width: 250px;\r\n");
      out.write("        padding-left: 125px;   \r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("            <hr>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div class=\"footerbar\">\r\n");
      out.write("            <div class=\"minLogo\">\r\n");
      out.write("                <div>\r\n");
      out.write("                 <image src=\"resources/images/mainLogo.png\" width=\"300\" height=\"60\"></image>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ex\">\r\n");
      out.write("             <div class=\"ect\">\r\n");
      out.write("                    본사 : 서울특별시 강남구 테헤란로 14길 6 남도빌딩 3F, 4F, 5F<br><br>\r\n");
      out.write("            \r\n");
      out.write("                    상호 : (주) 코니멀 대표자: 김현솔 | 사업자 등록번호 : 987-65-12345 <br><br>    \r\n");
      out.write("                \r\n");
      out.write("                    신고 : 112 | 개인정보보호책임자 : 김아무개<br><br> \r\n");
      out.write("          \r\n");
      out.write("                    TEL : 1235-9876 | FAX : 02 - 1234 - 9876 | 이메일  :  conimal@gmail.com\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            <div class=\"call\">\r\n");
      out.write("                <div class=\"ect2\" >\r\n");
      out.write("                    고객센터\r\n");
      out.write("                    <div class=\"ect3\">\r\n");
      out.write("                    1235-9876\r\n");
      out.write("                                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"ect\" id=\"al\">                    \r\n");
      out.write("                    평일 : 10:00-16:00<br>\r\n");
      out.write("                    점심시간 : 13:00-14:00<br>\r\n");
      out.write("                    (토/일/공휴일은 휴뮤입니다.)                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
